### PR TITLE
fix: value not set

### PR DESCRIPTION
**Pull request by mbystedt**

### CODE REVIEW

**Review by andrwils — APPROVED** [review]

**Comment by webgismd** [comment]
question.. why is this is using timestampTimezone: 'America/New_York',? (-5 UTC) vs https://en.wikipedia.org/wiki/UTC%E2%88%9208:00  (or [America/Los_Angeles] or [US/Pacific](https://en.wikipedia.org/wiki/Pacific_Time_Zone)

**Comment by mbystedt** [comment]
Ha. It’s like a laid a trap! That’s in a test and was specifically chosen because it isn’t what we use. So, it won’t accidentally be right.

**Comment by webgismd** [comment]
oooh cool so will it will fix timezone issues?

**Comment by mbystedt** [comment]
Yes 🎉

**Comment by Rrbh198** [comment]
I was hacked, you guys weren't talking to me the actual prime holder of this account you guys were talking to the guy who lives in Nigeria who hacked me

Sent from Yahoo Mail on Android 
 
  On Tue, Mar 8, 2022 at 2:51 PM, Matthew ***@***.***> wrote:   


Yes 🎉
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
